#!/usr/bin/env bash

nino_version="0.0.1"

function import_config() {
  local project_config_file="./.nino/config"
  local global_config_file="$HOME/.ninorc"

  if [ -f $global_config_file  ]; then
    export $(cat $global_config_file)
  fi

  export $(cat $project_config_file)
  if [ -z "$target_env" ]; then
    export target_env=$default_target_env
  fi
  export target_name="${target_env}-${project_name}"
}


function help_command() {

  if [ -d .nino ]; then
    for task_script in .nino/*; do
      local task_name=$(basename $task_script)
      if [ "$task_name" != "config" ]; then
        echo $task_name
      fi
    done
  else
    echo "--no project config found--"
  fi

}


import_config
callback_args="${@:2}"

case $1 in

"--version")
  nino_version $callback_args;;

"help")
  help_command $callback_args;;

*)
  .nino/$1 $callback_args;;
esac
