#!/usr/bin/env python

import unittest
import commands


class TestEnvVars(unittest.TestCase):

    def test_env_vars_are_used(self):
        exit_code, task_output = commands.getstatusoutput('PATH=$(pwd):$PATH nino footask')

        print task_output
        task_output = task_output.split("\n")
        self.assertEqual(task_output[0], "echo test")
        self.assertEqual(task_output[1], "echo nino")
        self.assertEqual(task_output[2], "echo test-nino")
        self.assertEqual(task_output[3], "echo ok")


if __name__ == '__main__':
    unittest.main()
